# Generated by Django 4.2.5 on 2023-11-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='static/media/bokatak_img/alergiak')),
            ],
        ),
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAN', models.CharField(max_length=10)),
                ('izena', models.CharField(max_length=20)),
                ('abizena', models.CharField(max_length=20)),
                ('abizena2', models.CharField(max_length=20)),
                ('telefonoa', models.CharField(max_length=20)),
                ('helbidea', models.CharField(max_length=100)),
                ('postakodea', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='static/media/user_img')),
            ],
        ),
        migrations.CreateModel(
            name='Deskontua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eskaera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egoera', models.BooleanField(default=True)),
                ('id_bezeroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HozkadaBokatak.bezeroa')),
            ],
        ),
        migrations.CreateModel(
            name='Platerra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('deskribapena', models.CharField(max_length=1000)),
                ('mota', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='static/media/bokatak_img/bokatak')),
            ],
        ),
        migrations.CreateModel(
            name='Platerra_Eskaera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eskaera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HozkadaBokatak.eskaera')),
                ('platerra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HozkadaBokatak.platerra')),
            ],
        ),
        migrations.CreateModel(
            name='Deskontua_Platerra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskontua_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HozkadaBokatak.deskontua')),
                ('platerra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HozkadaBokatak.platerra')),
            ],
        ),
        migrations.CreateModel(
            name='Alergia_Platerra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HozkadaBokatak.alergia')),
                ('platerra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HozkadaBokatak.platerra')),
            ],
        ),
    ]
