# Generated by Django 4.2.5 on 2023-11-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0003_platerra_prezioa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergia',
            name='img',
            field=models.ImageField(upload_to='media/bokatak_img/alergiak'),
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='img',
            field=models.ImageField(upload_to='media/user_img'),
        ),
        migrations.AlterField(
            model_name='platerra',
            name='img',
            field=models.ImageField(upload_to='media/bokatak_img/bokatak'),
        ),
    ]
