# Generated by Django 4.2.5 on 2023-11-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0004_alter_alergia_img_alter_bezeroa_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergia',
            name='img',
            field=models.ImageField(upload_to='img/alergiak'),
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='img',
            field=models.ImageField(upload_to='img/erabiltzaileak'),
        ),
        migrations.AlterField(
            model_name='platerra',
            name='img',
            field=models.ImageField(upload_to='img/bokatak'),
        ),
    ]
