# Generated by Django 3.1.4 on 2023-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0005_alter_alergia_img_alter_bezeroa_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroa',
            name='emaila',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deskontua',
            name='ehunekoa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deskontua',
            name='kantitatea',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eskaera',
            name='eskaera_data',
            field=models.DateField(default='2017-01-01'),
        ),
        migrations.AddField(
            model_name='platerra',
            name='alergiak',
            field=models.ManyToManyField(blank=True, to='HozkadaBokatak.Alergia'),
        ),
        migrations.AddField(
            model_name='platerra_eskaera',
            name='kantitatea',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alergia',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='alergia_platerra',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bezeroa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deskontua',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deskontua_platerra',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eskaera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platerra',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platerra_eskaera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
