# Generated by Django 3.1.4 on 2023-11-07 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HozkadaBokatak', '0006_auto_20231107_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroa',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
