# Generated by Django 3.1.4 on 2023-11-06 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0007_remove_eskaera_eskaera_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskaera',
            name='eskaera_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 12, 55, 36, 372057, tzinfo=utc)),
        ),
    ]
