# Generated by Django 3.1.4 on 2023-11-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0008_auto_20231107_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezeroa',
            name='img',
            field=models.ImageField(default='img/erabiltzaileak/ico_arrainak.png', upload_to='img/erabiltzaileak'),
        ),
    ]
