# Generated by Django 4.2.6 on 2023-11-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0010_remove_platerra_deskontua_alter_alergia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskaera',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default="2017-01-10"),
            preserve_default=False,
        ),
    ]
