# Generated by Django 3.1.4 on 2023-11-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0011_auto_20231106_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskaera',
            name='eskaera_data',
            field=models.DateTimeField(null=True),
        ),
    ]
