# Generated by Django 4.2.6 on 2023-11-12 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0011_eskaera_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskaera',
            name='eskaera_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
