# Generated by Django 3.1.4 on 2023-11-06 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0013_auto_20231106_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskaera',
            name='eskaera_data',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 13, 12, 2, 546987, tzinfo=utc)),
        ),
    ]
