# Generated by Django 4.2.6 on 2023-11-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0014_alter_alergia_id_alter_alergia_platerra_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bezeroa',
            name='bidalketaKostua',
            field=models.FloatField(default=0),
        ),
    ]
