# Generated by Django 3.1.4 on 2023-11-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HozkadaBokatak', '0015_remove_eskaera_eskaera_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eskaera',
            name='eskaera_data',
            field=models.DateField(null=True),
        ),
    ]
